# spring boot configuration

welcome:
   message: Welcome to PosLedger Assets

spring:
   jpa:
      jpagenerate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   
      # update while chainging database
      hibernate:
         ddl-auto: update
      
      properties:
         hibernate:
            show_sql=true
            format_sql=true
            use_sql_comments=true
   
   # datasource configuration
   datasource:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.193.116:23306/jmrpadb?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: test02
      password: test1234
      platform: mysql
      tomcat:
         max-wait: 10000
         max-active: 50
         test-on-borrow: true

   http: 
      encoding:
         force: true
         force-request: true
         force-response: true

# server configuration
server:
   compression:
      enabled: false
      
   servlet:
      context-path: /assets
      
   port: 8080
   
   server:
      tomcat:
         uri-encoding: UTF-8

# log level
logging:
   level:
      org:
         springframework: info
         hibernate: error
  